### ISSUE TITLE
Errors whether installed with pip2 or pip (Python 3.4)

### ISSUE THREAD

**Issue by zenware** [glyph/horsephrase#7]
I tried installing this with pip2, python version 2.7.5 and pip, python version 3.4.5.
```
pip -V
pip 9.0.1 from /usr/lib/python3.4/site-packages/pip-9.0.1-py3.4.egg (python 3.4)
```

Each time I tried installing the tool I got the following error:
```
Successfully built horsephrase
Installing collected packages: horsephrase
Successfully installed horsephrase-0.5.0
$ horsephrase 
Traceback (most recent call last):
  File "/usr/bin/horsephrase", line 7, in <module>
    from horsephrase.__main__ import main
ImportError: No module named 'horsephrase.__main__'
```

I think it's weird because in site-packages there's this: `/usr/lib/python3.4/site-packages/horsephrase/__main__.py`
That indicates to me that there is a module with such a name.

**Comment by glyph** [comment]
This works for me on the latest patch versions of the Pythons specified, so I'm going to call this one a "worksforme" :).  If it is a bug, it's probably a bug in setuptools; you'll need to post the exact versions of everything else you're using, as well as your OS, if anyone else is to have any luck diagnosing.

FYI: Python 2.7.5 is unsupported and contains dangerous security issues.  Please upgrade to AT LEAST Python 2.7.9 immediately.

**Comment by glyph** [comment]
(Oh, but let me not forget to say: thank you for using horsephrase, and thank you for the report!  Sorry it's not working for you.)

**Comment by zenware** [comment]
In my case Python 2.7.5 is that in version name only and is technically a patched build, I know dumb, but whatever.

CentOS 7 - 3.10.0-514.26.2.el7.x86_64

And it does work inside a virtualenv so I guess it's not a problem after all...

However, with Python 3.6.2 when I `venv/bin/pip install horsephrase` and then attempt `venv/bin/horsephrase generate` I get some other awesome output:
```
$ venv/bin/horsephrase generate
Traceback (most recent call last):
  File "venv/bin/horsephrase", line 11, in <module>
    sys.exit(main())
  File "/home/usryly/Workspace/Trash/venv/lib/python3.6/site-packages/horsephrase/__main__.py", line 113, in main
    namespace.do_verb(namespace)
  File "/home/usryly/Workspace/Trash/venv/lib/python3.6/site-packages/horsephrase/__main__.py", line 15, in do_generate
    joiner=namespace.joiner))
  File "/home/usryly/Workspace/Trash/venv/lib/python3.6/site-packages/horsephrase/_implementation.py", line 15, in generate
    return joiner.join(choice(words) for each in range(number))
TypeError: sequence item 0: expected str instance, bytes found
```
The same results with 3.4.7 - So I'm not sure what you meant by 'the latest patch of the python versions specified' but that didn't do the trick for me either.

Did get it to work with Python 2.7.13 in a venv
```
venv/bin/horsephrase generate
precise inventing streamline installed comprises
```

To be clear, I'm not especially worried that it's "not working for me". Just whenever I encounter any issues I think it's better to be public about them than not to reveal them at all.

Also, your classifiers list is just "Programming Language :: Python :: 2.7" which means a user ought to be able to use 2.7.5 without troubles. (Anyways my best guess is I trashed the OS permissions. I'll look more into it and try to get back to you on that.)
So since you don't actually claim support for Python 3 in the setup I'm inclined at this point to think that Python version 3.x is part of the problem. I'll try to look more into what's up with the system version of 2.7 and get back to you on that though, maybe it will be useful, maybe not.

Finally, thanks for Twisted :+1:

**Comment by glyph** [comment]
> In my case Python 2.7.5 is that in version name only and is technically a patched build, I know dumb, but whatever.
> 
> CentOS 7 - 3.10.0-514.26.2.el7.x86_64

All I can say about this is covered in https://alexgaynor.net/2015/mar/30/red-hat-open-source-community/ .  (Although in this case I very much doubt the bug here has anything to do with your patched python version.)

> However, with Python 3.6.2 when I venv/bin/pip install horsephrase and then attempt venv/bin/horsephrase generate I get some other awesome output:

Yup, not supported on Py3 yet.  I'd love a PR for this, since I switched my own `pipsi` installation over to py3 and I keep having to reinstall horsephrase with py2 explicitly every time I install it :-).

> To be clear, I'm not especially worried that it's "not working for me". Just whenever I encounter any issues I think it's better to be public about them than not to reveal them at all.

Absolutely!  Bug reports are welcome.  Just in this case I don't think the bug actually has anything to do with horsephrase.

> Finally, thanks for Twisted 👍

1. kind of you to say so, and
2. thanks for using it!
